### ISSUE TITLE
Unclearable gap, had to use noclip

### ISSUE THREAD

**Issue by mridlen** [caligari87/ObAddon#82] opened 2020-06-24 00:22 UTC
![Screenshot_Doom_20200623_103805](https://user-images.githubusercontent.com/5098180/85481125-d9a5fa80-b586-11ea-8b60-d68b5f966e6d.png)

**Comment by GTD-Carthage** [comment] 2020-07-06 02:17
This should be fixed on the newest build - this is caused by room symmetry and some certain shape rule passes interfering with each other.

**Closed as completed by GTD-Carthage** 2020-07-06 02:17 UTC
Labels: bug, question
