### ISSUE TITLE
Script Error: assertion failed!

### ISSUE THREAD

**Issue by CaptainNurbles** [caligari87/ObAddon#85] opened 2020-06-26 23:21 UTC
With the new release of Obaddon any time I try to build a full length megawad, 95% of the time it fails partway through throwing up an error saying "Script Error: assertion failed!" Not a clue what it means. Smaller map sets have a higher success chance. Often times when a megawad is almost finished it'll fail when building map31.

**Comment by Kokokokoka** [comment] 2020-07-04 08:24
Can confirm this. Wanted to build a heretic wad and had no luck from the first map.
It would have been better if one knew, what does this assert means or (and) where it fails.
In windows there is a message though: Script error: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by GTD-Carthage** [comment] 2020-07-05 09:49
Assertion errors can be caused by just anywhere in the code where there is an assert statement - a stacktrace of the issues can be found in the LOGS.txt generated in the same directory as your Oblige binary.

Heretic level generation is currently lagging behind but has received some fixes - I recommend trying the cutting edge version of ObAddon instead. I will be closing this for now.

**Closed as completed by GTD-Carthage** 2020-07-05 09:49 UTC
