### ISSUE TITLE
Crash when generating a streets episode

### ISSUE THREAD

**Issue by Demiosis** [caligari87/ObAddon#19] opened 2019-03-15 06:47 UTC
Crash log: Version: The one just before: Added a 3 seed wide template

[crash.txt](https://github.com/caligari87/ObAddon/files/2969732/crash.txt)

**Comment by GTD-Carthage** [comment] 2019-03-15 11:20
This seems to be caused by my extra entrance sprout rules for street rooms... oddly enough, it seemed the connection between the first room and the second was interrupted by another room, which is something that shouldn't happen... though I think I'll be disabling those extra sprout rules instead seeing as they seem to frequently just create things like tiny rooms...

**Comment by Demiosis** [comment] 2019-03-15 23:21
tiny rooms are fine but not if there'S tons of them.. XD

**Comment by GTD-Carthage** [comment] 2019-03-17 14:11
This should be fixed now (I disabled the extra sprout rules that *may* have caused this), so I'll close the issue for now - if it still shows up though, can probably open this up again. :)

**Closed as completed by GTD-Carthage** 2019-03-17 14:11 UTC
